name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - master
env:
  PYANY_USER: ${{ secrets.PYANY_USER }}
  PYANY_KEY: ${{ secrets.PYANY_KEY }}
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Updated Code
      uses: actions/checkout@v2
      
    - name: Start Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
      
    - name: Install PythonAnywhere API
      run: |
        sudo apt-get update
        sudo apt-get install -y rsync
        pip install --upgrade pythonanywhere
      
    - name: Deploy Back End to PythonAnywhere
      run: |
        python -c "from pythonanywhere import upload; upload(username='$PYANY_USER', token='$PYANY_KEY', src='./', dst='/home/$PYANY_USER/mysite')"
